import { POC, Severity, Category } from './types';

export const POC_DATABASE: POC[] = [
  {
    id: 'POC-RECON-001', name: 'ICMP Host Discovery',
    category: Category.RECON, severity: Severity.LOW, cvssScore: 0.0,
    pocFile: 'reconnaissance/01_ICMP_Host_Discovery.py',
    description: 'ICMP Ping检测目标主机是否在线',
    impact: '主机信息泄露',
    remediation: '配置防火墙过滤ICMP',
    requiredParams: ['ip'],
    codeSnippet: '# ICMP Host Discovery',
  },
  {
    id: 'POC-RECON-002', name: 'TCP Port Scan',
    category: Category.RECON, severity: Severity.MEDIUM, cvssScore: 5.0,
    pocFile: 'reconnaissance/02_TCP_Port_Scan.py',
    description: '扫描IVI系统Top-50常见TCP端口',
    impact: '发现开放服务和攻击面',
    remediation: '关闭不必要端口',
    requiredParams: ['ip'],
    codeSnippet: '# TCP Port Scan',
  },
  {
    id: 'POC-RECON-003', name: 'mDNS Service Discovery',
    category: Category.RECON, severity: Severity.LOW, cvssScore: 3.0,
    pocFile: 'reconnaissance/03_mDNS_Service_Discovery.py',
    description: '通过mDNS多播查询发现AirPlay/CarPlay/DLNA等服务',
    impact: '服务信息暴露',
    remediation: '禁用不必要的mDNS服务',
    requiredParams: ['ip'],
    codeSnippet: '# mDNS Service Discovery',
  },
  {
    id: 'POC-RECON-004', name: 'UPnP/SSDP Discovery',
    category: Category.RECON, severity: Severity.LOW, cvssScore: 3.0,
    pocFile: 'reconnaissance/04_UPnP_SSDP_Discovery.py',
    description: '通过SSDP M-SEARCH广播发现UPnP设备',
    impact: '设备和服务信息泄露',
    remediation: '禁用UPnP',
    requiredParams: ['ip'],
    codeSnippet: '# UPnP/SSDP Discovery',
  },
  {
    id: 'POC-RECON-005', name: 'SNMP Community String Check',
    category: Category.RECON, severity: Severity.MEDIUM, cvssScore: 5.5,
    pocFile: 'reconnaissance/05_SNMP_Info_Leak.py',
    description: '检测SNMP服务是否使用默认community string',
    impact: '设备配置信息泄露',
    remediation: '修改默认SNMP community',
    requiredParams: ['ip'],
    codeSnippet: '# SNMP Community String Check',
  },
  {
    id: 'POC-RECON-006', name: 'Bluetooth SDP Enumeration',
    category: Category.RECON, severity: Severity.LOW, cvssScore: 3.0,
    pocFile: 'reconnaissance/06_BT_SDP_Enum.py',
    description: '枚举目标蓝牙设备SDP服务记录',
    impact: '蓝牙攻击面发现',
    remediation: '限制SDP查询',
    requiredParams: ['bluetooth_mac'],
    codeSnippet: '# Bluetooth SDP Enumeration',
  },
  {
    id: 'POC-RECON-007', name: 'T-Box/TCU Port Scan',
    category: Category.RECON, severity: Severity.MEDIUM, cvssScore: 5.0,
    pocFile: 'reconnaissance/07_TBOX_Port_Scan.py',
    description: '扫描T-Box/TCU特有端口(MQTT/OTA/诊断等)',
    impact: '远程管理服务暴露',
    remediation: '限制T-Box网络暴露面',
    requiredParams: ['ip'],
    codeSnippet: '# T-Box/TCU Port Scan',
  },
  {
    id: 'POC-RECON-008', name: 'HTTP Service Enumeration',
    category: Category.RECON, severity: Severity.MEDIUM, cvssScore: 5.0,
    pocFile: 'reconnaissance/08_HTTP_Service_Enum.py',
    description: '扫描常见Web端口,获取Server信息',
    impact: 'Web服务信息泄露',
    remediation: '禁用不必要的Web服务',
    requiredParams: ['ip'],
    codeSnippet: '# HTTP Service Enumeration',
  },
  {
    id: 'POC-NET-001', name: 'ADB Debug Port Detection',
    category: Category.NETWORK, severity: Severity.CRITICAL, cvssScore: 9.8,
    cveId: 'CVE-2018-6242',
    pocFile: 'network/09_ADB_Debug_Port.py',
    description: '检测ADB TCP:5555端口是否开放并尝试握手',
    impact: '远程Shell未授权访问',
    remediation: '禁用ADB over TCP',
    requiredParams: ['ip'],
    codeSnippet: '# ADB Debug Port Detection',
  },
  {
    id: 'POC-NET-002', name: 'SSH Weak Credentials',
    category: Category.NETWORK, severity: Severity.HIGH, cvssScore: 8.0,
    pocFile: 'network/10_SSH_Weak_Creds.py',
    description: '车机SSH服务弱口令检测(12组常见默认密码)',
    impact: '远程Root Shell访问',
    remediation: '使用强密码或禁用SSH',
    requiredParams: ['ip'],
    codeSnippet: '# SSH Weak Credentials',
  },
  {
    id: 'POC-NET-003', name: 'SSH Hardcoded Credentials',
    category: Category.NETWORK, severity: Severity.CRITICAL, cvssScore: 9.8,
    pocFile: 'network/11_SSH_Hardcoded_Creds.py',
    description: '检测IVI系统SSH硬编码凭据(falcOn/harman_fara等)',
    impact: 'Root Shell访问',
    remediation: '修改默认凭据,禁用生产环境SSH',
    requiredParams: ['ip'],
    codeSnippet: '# SSH Hardcoded Credentials',
  },
  {
    id: 'POC-NET-004', name: 'Telnet Service Detection',
    category: Category.NETWORK, severity: Severity.HIGH, cvssScore: 7.5,
    pocFile: 'network/12_Telnet_Service.py',
    description: '检测Telnet服务是否开放(明文传输风险)',
    impact: '凭据窃听,远程访问',
    remediation: '禁用Telnet,使用SSH替代',
    requiredParams: ['ip'],
    codeSnippet: '# Telnet Service Detection',
  },
  {
    id: 'POC-NET-005', name: 'FTP Anonymous Login',
    category: Category.NETWORK, severity: Severity.HIGH, cvssScore: 7.5,
    pocFile: 'network/13_FTP_Anonymous.py',
    description: '检测FTP服务是否允许匿名登录',
    impact: '文件系统未授权访问',
    remediation: '禁用匿名FTP',
    requiredParams: ['ip'],
    codeSnippet: '# FTP Anonymous Login',
  },
  {
    id: 'POC-NET-006', name: 'MQTT Unauthenticated Subscribe',
    category: Category.NETWORK, severity: Severity.HIGH, cvssScore: 7.0,
    pocFile: 'network/14_MQTT_Unauth.py',
    description: '检测MQTT Broker是否允许匿名连接和通配符订阅',
    impact: '车辆遥测数据泄露',
    remediation: '启用MQTT认证',
    requiredParams: ['ip'],
    codeSnippet: '# MQTT Unauthenticated Subscribe',
  },
  {
    id: 'POC-NET-007', name: 'D-Bus Anonymous Authentication',
    category: Category.NETWORK, severity: Severity.CRITICAL, cvssScore: 9.0,
    cveId: 'CVE-2015-5611',
    pocFile: 'network/15_DBus_Anon_Auth.py',
    description: 'D-Bus服务通过TCP:6667接受匿名认证',
    impact: '通过D-Bus方法调用控制车辆',
    remediation: '限制D-Bus为本地,启用认证',
    requiredParams: ['ip'],
    codeSnippet: '# D-Bus Anonymous Authentication',
  },
  {
    id: 'POC-NET-008', name: 'RTSP Log Information Leak',
    category: Category.NETWORK, severity: Severity.MEDIUM, cvssScore: 5.5,
    pocFile: 'network/16_RTSP_Log_Leak.py',
    description: 'RTSP ANY请求检测端口7000未授权日志访问',
    impact: '系统日志信息泄露',
    remediation: 'RTSP端点启用认证',
    requiredParams: ['ip'],
    codeSnippet: '# RTSP Log Information Leak',
  },
  {
    id: 'POC-NET-009', name: 'DLNA AVTransport Unauth Control',
    category: Category.NETWORK, severity: Severity.MEDIUM, cvssScore: 6.0,
    pocFile: 'network/17_DLNA_AVTransport_Unauth.py',
    description: 'SSDP发现+未授权SetAVTransportURI命令',
    impact: '媒体注入和屏幕控制',
    remediation: '禁用UPnP或启用认证',
    requiredParams: ['ip'],
    codeSnippet: '# DLNA AVTransport Unauth Control',
  },
  {
    id: 'POC-NET-010', name: 'HTTPS Missing Certificate Pinning',
    category: Category.NETWORK, severity: Severity.MEDIUM, cvssScore: 5.5,
    pocFile: 'network/18_HTTPS_No_Cert_Pin.py',
    description: '检测HTTPS更新通道是否缺少证书固定',
    impact: '中间人攻击OTA更新',
    remediation: '实施证书固定',
    requiredParams: [],
    codeSnippet: '# HTTPS Missing Certificate Pinning',
  },
  {
    id: 'POC-PROT-001', name: 'CAN Bus Traffic Capture',
    category: Category.CANBUS, severity: Severity.MEDIUM, cvssScore: 5.0,
    pocFile: 'canbus/19_CAN_Bus_Sniff.py',
    description: '捕获CAN总线流量,分析帧ID分布和数据模式',
    impact: '总线通信信息分析',
    remediation: '实施CAN总线加密',
    requiredParams: ['can_interface'],
    codeSnippet: '# CAN Bus Traffic Capture',
  },
  {
    id: 'POC-PROT-002', name: 'CAN Message Injection',
    category: Category.CANBUS, severity: Severity.CRITICAL, cvssScore: 9.0,
    pocFile: 'canbus/20_CAN_Message_Injection.py',
    description: '注入UDS TesterPresent帧,验证CAN总线认证机制',
    impact: '任意ECU控制',
    remediation: '实施CAN认证(SecOC)',
    requiredParams: ['can_interface'],
    codeSnippet: '# CAN Message Injection',
  },
  {
    id: 'POC-PROT-003', name: 'CAN Bus DoS Flood',
    category: Category.CANBUS, severity: Severity.HIGH, cvssScore: 7.5,
    pocFile: 'canbus/21_CAN_DoS_Flood.py',
    description: '高优先级CAN帧洪泛测试总线拒绝服务风险',
    impact: 'ECU通信中断',
    remediation: '实施CAN总线IDS',
    requiredParams: ['can_interface'],
    codeSnippet: '# CAN Bus DoS Flood',
  },
  {
    id: 'POC-PROT-004', name: 'CAN Replay Attack',
    category: Category.CANBUS, severity: Severity.HIGH, cvssScore: 7.0,
    pocFile: 'canbus/22_CAN_Replay_Attack.py',
    description: '录制并重放CAN帧,验证是否缺少序列号保护',
    impact: '重放历史指令',
    remediation: '添加帧序列号/时间戳',
    requiredParams: ['can_interface'],
    codeSnippet: '# CAN Replay Attack',
  },
  {
    id: 'POC-PROT-005', name: 'UDS Diagnostic Session Bypass',
    category: Category.CANBUS, severity: Severity.HIGH, cvssScore: 7.5,
    pocFile: 'canbus/23_UDS_DiagSession_Bypass.py',
    description: '尝试UDS 0x10直接进入扩展诊断/编程会话',
    impact: '未授权诊断访问',
    remediation: '实施UDS会话认证',
    requiredParams: ['can_interface'],
    codeSnippet: '# UDS Diagnostic Session Bypass',
  },
  {
    id: 'POC-PROT-006', name: 'UDS Security Access Brute Force',
    category: Category.CANBUS, severity: Severity.CRITICAL, cvssScore: 8.5,
    pocFile: 'canbus/24_UDS_Security_Access_Brute.py',
    description: 'UDS 0x27安全访问Seed-Key暴力破解',
    impact: 'ECU安全锁定绕过',
    remediation: '实施强Seed-Key算法,添加尝试限制',
    requiredParams: ['can_interface'],
    codeSnippet: '# UDS Security Access Brute Force',
  },
  {
    id: 'POC-PROT-007', name: 'UDS ReadMemoryByAddress',
    category: Category.CANBUS, severity: Severity.CRITICAL, cvssScore: 8.5,
    pocFile: 'canbus/25_UDS_ReadMemory.py',
    description: 'UDS 0x23服务未授权读取ECU内存',
    impact: '固件/密钥/配置泄露',
    remediation: '限制内存读取服务',
    requiredParams: ['can_interface'],
    codeSnippet: '# UDS ReadMemoryByAddress',
  },
  {
    id: 'POC-PROT-008', name: 'UDS RoutineControl Abuse',
    category: Category.CANBUS, severity: Severity.CRITICAL, cvssScore: 8.0,
    pocFile: 'canbus/26_UDS_RoutineControl.py',
    description: 'UDS 0x31服务未授权执行ECU例程(擦除/重置等)',
    impact: 'ECU功能篡改',
    remediation: '例程执行需安全访问',
    requiredParams: ['can_interface'],
    codeSnippet: '# UDS RoutineControl Abuse',
  },
  {
    id: 'POC-PROT-009', name: 'OBD-II VIN Spoofing',
    category: Category.CANBUS, severity: Severity.MEDIUM, cvssScore: 5.0,
    pocFile: 'canbus/27_OBD_VIN_Spoof.py',
    description: '通过CAN注入伪造VIN响应',
    impact: '车辆身份伪造',
    remediation: 'VIN完整性校验',
    requiredParams: ['can_interface'],
    codeSnippet: '# OBD-II VIN Spoofing',
  },
  {
    id: 'POC-PROT-010', name: 'QNX Qnet Unauthorized File Read',
    category: Category.WIRELESS, severity: Severity.CRITICAL, cvssScore: 9.1,
    cveId: 'CVE-2017-3891',
    pocFile: 'wireless/28_QNX_Qnet_File_Read.py',
    description: 'Qnet/Qconn服务暴露允许远程读取敏感文件',
    impact: '文件系统完全访问',
    remediation: '禁用Qnet over TCP,配置防火墙',
    requiredParams: ['ip'],
    codeSnippet: '# QNX Qnet Unauthorized File Read',
  },
  {
    id: 'POC-WIFI-001', name: 'WiFi Deauthentication Attack',
    category: Category.WIRELESS, severity: Severity.MEDIUM, cvssScore: 6.5,
    pocFile: 'wireless/29_WiFi_Deauth.py',
    description: '发送802.11 Deauth帧测试PMF保护',
    impact: '无线连接中断',
    remediation: '启用802.11w PMF',
    requiredParams: ['interface'],
    codeSnippet: '# WiFi Deauthentication Attack',
  },
  {
    id: 'POC-WIFI-002', name: 'WiFi Evil Twin AP',
    category: Category.WIRELESS, severity: Severity.HIGH, cvssScore: 7.0,
    pocFile: 'wireless/30_WiFi_Evil_Twin.py',
    description: '创建同名伪造AP测试自动连接行为',
    impact: '流量劫持/凭据窃取',
    remediation: '实施AP认证,禁用自动连接',
    requiredParams: ['interface'],
    codeSnippet: '# WiFi Evil Twin AP',
  },
  {
    id: 'POC-WIFI-003', name: 'WPA2 KRACK Key Reinstallation',
    category: Category.WIRELESS, severity: Severity.HIGH, cvssScore: 6.8,
    cveId: 'CVE-2017-13077',
    pocFile: 'wireless/31_WiFi_KRACK.py',
    description: 'WPA2 4-way handshake密钥重装攻击检测',
    impact: '加密流量解密',
    remediation: '更新至WPA3或打补丁',
    requiredParams: ['interface'],
    codeSnippet: '# WPA2 KRACK Key Reinstallation',
  },
  {
    id: 'POC-WIFI-004', name: 'TI WL18xx WiFi Driver Overflow',
    category: Category.WIRELESS, severity: Severity.CRITICAL, cvssScore: 9.6,
    cveId: 'CVE-2023-29468',
    pocFile: 'wireless/32_WiFi_TI_WL18xx_Overflow.py',
    description: '超大Vendor IE的WiFi Beacon触发TI WL18xx驱动溢出',
    impact: '远程代码执行',
    remediation: '更新WiFi驱动固件',
    requiredParams: ['interface'],
    codeSnippet: '# TI WL18xx WiFi Driver Overflow',
  },
  {
    id: 'POC-WIFI-005', name: 'ConnMan DHCP Buffer Overflow',
    category: Category.WIRELESS, severity: Severity.CRITICAL, cvssScore: 9.8,
    cveId: 'CVE-2021-26675',
    pocFile: 'wireless/33_ConnMan_DHCP_Overflow.py',
    description: '恶意DHCP Offer超长hostname溢出ConnMan',
    impact: 'WiFi远程代码执行',
    remediation: '更新ConnMan,验证DHCP选项长度',
    requiredParams: ['ip', 'interface'],
    codeSnippet: '# ConnMan DHCP Buffer Overflow',
  },
  {
    id: 'POC-WIFI-006', name: 'Broadcom WME IE Overflow',
    category: Category.WIRELESS, severity: Severity.CRITICAL, cvssScore: 9.8,
    cveId: 'CVE-2017-9417',
    pocFile: 'wireless/34_Broadcom_WME_Overflow.py',
    description: '畸形WME Information Element利用Broadcom WiFi固件漏洞',
    impact: 'WiFi芯片远程代码执行',
    remediation: '更新Broadcom WiFi固件',
    requiredParams: ['interface'],
    codeSnippet: '# Broadcom WME IE Overflow',
  },
  {
    id: 'POC-WIFI-007', name: 'WiFi Unauthenticated Vehicle Control',
    category: Category.WIRELESS, severity: Severity.HIGH, cvssScore: 7.5,
    pocFile: 'wireless/35_WiFi_Unauth_Vehicle_Ctrl.py',
    description: '通过WiFi发送未认证车辆控制命令',
    impact: '未授权控制车灯/HVAC/警报',
    remediation: '控制命令添加认证',
    requiredParams: ['ip'],
    codeSnippet: '# WiFi Unauthenticated Vehicle Control',
  },
  {
    id: 'POC-BT-001', name: 'Bluetooth HFP AT Command Overflow',
    category: Category.WIRELESS, severity: Severity.HIGH, cvssScore: 7.8,
    cveId: 'CVE-2025-32059',
    pocFile: 'wireless/36_BT_HFP_AT_Overflow.py',
    description: '畸形+ANDROID AT命令溢出HFP解析器栈',
    impact: '蓝牙栈崩溃/潜在RCE',
    remediation: '更新蓝牙固件,验证AT命令长度',
    requiredParams: ['bluetooth_mac'],
    codeSnippet: '# Bluetooth HFP AT Command Overflow',
  },
  {
    id: 'POC-BT-002', name: 'BLUFFS Session Key Downgrade',
    category: Category.WIRELESS, severity: Severity.HIGH, cvssScore: 6.8,
    cveId: 'CVE-2023-24023',
    pocFile: 'wireless/37_BT_BLUFFS_Key_Downgrade.py',
    description: '强制Bluetooth BR/EDR协商最短密钥(entropy=1)',
    impact: '加密会话可被破解',
    remediation: '更新至BT 5.4+,实施密钥长度策略',
    requiredParams: ['bluetooth_mac'],
    codeSnippet: '# BLUFFS Session Key Downgrade',
  },
  {
    id: 'POC-BT-003', name: 'BlueSDK L2CAP Null CID (PerfektBlue)',
    category: Category.WIRELESS, severity: Severity.CRITICAL, cvssScore: 8.8,
    cveId: 'CVE-2024-45431',
    pocFile: 'wireless/38_BT_PerfektBlue_L2CAP.py',
    description: 'BlueSDK L2CAP远程CID验证不当,null CID触发RCE',
    impact: 'IVI系统远程代码执行',
    remediation: '更新BlueSDK蓝牙栈',
    requiredParams: ['bluetooth_mac'],
    codeSnippet: '# BlueSDK L2CAP Null CID (PerfektBlue)',
  },
  {
    id: 'POC-BT-004', name: 'BlueSDK RFCOMM Confusion (PerfektBlue)',
    category: Category.WIRELESS, severity: Severity.HIGH, cvssScore: 7.5,
    cveId: 'CVE-2024-45432',
    pocFile: 'wireless/39_BT_PerfektBlue_RFCOMM.py',
    description: 'BlueSDK RFCOMM函数调用参数错误导致信息泄露',
    impact: '信息泄露/异常行为',
    remediation: '更新BlueSDK蓝牙栈',
    requiredParams: ['bluetooth_mac'],
    codeSnippet: '# BlueSDK RFCOMM Confusion (PerfektBlue)',
  },
  {
    id: 'POC-BT-005', name: 'Bluetooth HFP Use-After-Free',
    category: Category.WIRELESS, severity: Severity.CRITICAL, cvssScore: 9.0,
    cveId: 'CVE-2025-0084',
    pocFile: 'wireless/40_BT_HFP_UAF.py',
    description: 'BT HFP Profile UAF导致OOB写入和远程代码执行',
    impact: '零交互远程RCE',
    remediation: '更新蓝牙栈固件',
    requiredParams: ['bluetooth_mac'],
    codeSnippet: '# Bluetooth HFP Use-After-Free',
  },
  {
    id: 'POC-BT-006', name: 'Bluetooth Keystroke Injection',
    category: Category.WIRELESS, severity: Severity.HIGH, cvssScore: 7.5,
    cveId: 'CVE-2023-45866',
    pocFile: 'wireless/41_BT_Keystroke_Injection.py',
    description: '伪造BT键盘(CoD=0x002540)进行HID注入',
    impact: '未授权键盘输入注入',
    remediation: '要求用户确认BT HID配对',
    requiredParams: ['bluetooth_mac'],
    codeSnippet: '# Bluetooth Keystroke Injection',
  },
  {
    id: 'POC-BT-007', name: 'BlueBorne BNEP Heap Overflow',
    category: Category.WIRELESS, severity: Severity.CRITICAL, cvssScore: 8.8,
    cveId: 'CVE-2017-0781',
    pocFile: 'wireless/42_BlueBorne_BNEP_Overflow.py',
    description: '畸形BNEP控制帧触发Android BT栈堆溢出',
    impact: '零交互远程代码执行',
    remediation: '更新蓝牙协议栈',
    requiredParams: ['bluetooth_mac'],
    codeSnippet: '# BlueBorne BNEP Heap Overflow',
  },
  {
    id: 'POC-BT-008', name: 'BleedingTooth L2CAP Type Confusion',
    category: Category.WIRELESS, severity: Severity.CRITICAL, cvssScore: 8.3,
    cveId: 'CVE-2020-12351',
    pocFile: 'wireless/43_BleedingTooth_L2CAP.py',
    description: '畸形A2MP L2CAP包触发Linux内核类型混淆',
    impact: '内核级远程代码执行',
    remediation: '更新Linux内核,关闭不用的BT',
    requiredParams: ['bluetooth_mac'],
    codeSnippet: '# BleedingTooth L2CAP Type Confusion',
  },
  {
    id: 'POC-WIFI-008', name: 'AirPlay AirBorne UAF',
    category: Category.APPLICATION, severity: Severity.CRITICAL, cvssScore: 9.8,
    cveId: 'CVE-2025-24252',
    pocFile: 'application/44_AirPlay_AirBorne_UAF.py',
    description: 'AirPlay协议UAF漏洞+用户交互绕过实现零点击RCE',
    impact: '服务崩溃/远程代码执行',
    remediation: '更新AirPlay服务,限制mDNS',
    requiredParams: ['ip', 'interface'],
    codeSnippet: '# AirPlay AirBorne UAF',
  },
  {
    id: 'POC-APP-001', name: 'IVI USB Gadget SQL Injection',
    category: Category.APPLICATION, severity: Severity.HIGH, cvssScore: 6.8,
    cveId: 'CVE-2024-8355',
    pocFile: 'application/45_IVI_USB_SQLi.py',
    description: 'USB Gadget序列号SQL注入IVI数据库(CMU)',
    impact: '数据库访问/任意SQL执行',
    remediation: '对USB设备输入进行参数化处理',
    requiredParams: [],
    codeSnippet: '# IVI USB Gadget SQL Injection',
  },
  {
    id: 'POC-APP-002', name: 'CarPlay Protocol Stack Overflow',
    category: Category.APPLICATION, severity: Severity.HIGH, cvssScore: 7.5,
    cveId: 'CVE-2024-23923',
    pocFile: 'application/46_CarPlay_Stack_Overflow.py',
    description: '超大CarPlay协议数据包触发头单元栈溢出',
    impact: '远程崩溃或代码执行',
    remediation: '更新固件,验证数据包长度',
    requiredParams: ['ip'],
    codeSnippet: '# CarPlay Protocol Stack Overflow',
  },
  {
    id: 'POC-APP-003', name: 'HiQnet Audio Protocol Stack Overflow',
    category: Category.APPLICATION, severity: Severity.CRITICAL, cvssScore: 9.8,
    cveId: 'CVE-2021-23906',
    pocFile: 'application/47_HiQnet_Stack_Overflow_TCP.py',
    description: '畸形HiQnet头部(长度0xFFFFFFFF)触发TCP:3804栈溢出',
    impact: '远程代码执行或DoS',
    remediation: '修补HiQnet服务,限制网络访问',
    requiredParams: ['ip'],
    codeSnippet: '# HiQnet Audio Protocol Stack Overflow',
  },
  {
    id: 'POC-APP-004', name: 'HiQnet UDP Heap Overflow',
    category: Category.APPLICATION, severity: Severity.CRITICAL, cvssScore: 9.8,
    cveId: 'CVE-2021-23906',
    pocFile: 'application/48_HiQnet_Heap_Overflow_UDP.py',
    description: 'UDP数据包恶意count字段(0xFFFF)触发堆溢出',
    impact: '远程代码执行或DoS',
    remediation: '修补HiQnet,验证count字段',
    requiredParams: ['ip'],
    codeSnippet: '# HiQnet UDP Heap Overflow',
  },
  {
    id: 'POC-APP-005', name: 'WebView file:// Data Exfiltration',
    category: Category.APPLICATION, severity: Severity.MEDIUM, cvssScore: 5.0,
    pocFile: 'application/49_WebView_File_Exfil.py',
    description: 'WebView file:// URI访问窃取本地数据库',
    impact: '敏感数据窃取',
    remediation: '限制WebView file://访问,启用CSP',
    requiredParams: [],
    codeSnippet: '# WebView file:// Data Exfiltration',
  },
  {
    id: 'POC-APP-006', name: 'Filename Command Injection',
    category: Category.APPLICATION, severity: Severity.HIGH, cvssScore: 7.5,
    pocFile: 'application/50_Filename_Command_Injection.py',
    description: '恶意文件名Shell注入(;telnetd -p 4444;)',
    impact: '远程Shell',
    remediation: '对文件名进行转义处理',
    requiredParams: [],
    codeSnippet: '# Filename Command Injection',
  },
  {
    id: 'POC-APP-007', name: 'USB Path Traversal Injection',
    category: Category.APPLICATION, severity: Severity.CRITICAL, cvssScore: 8.5,
    pocFile: 'application/51_USB_Path_Injection.py',
    description: '恶意USB目录结构利用路径操作获取反弹Shell',
    impact: 'IVI反弹Shell',
    remediation: '路径输入清理',
    requiredParams: ['ip'],
    codeSnippet: '# USB Path Traversal Injection',
  },
  {
    id: 'POC-APP-008', name: 'IVI Developer Mode Bypass',
    category: Category.APPLICATION, severity: Severity.CRITICAL, cvssScore: 8.5,
    cveId: 'CVE-2025-32063',
    pocFile: 'application/52_IVI_DevMode_Bypass.py',
    description: 'BOSCH IVI启动时序攻击激活开发者模式',
    impact: '禁用防火墙+启动SSH',
    remediation: '移除生产环境开发者功能',
    requiredParams: ['ip'],
    codeSnippet: '# IVI Developer Mode Bypass',
  },
  {
    id: 'POC-APP-009', name: 'Wireless Dongle Auth Bypass',
    category: Category.APPLICATION, severity: Severity.CRITICAL, cvssScore: 8.8,
    cveId: 'CVE-2025-2765',
    pocFile: 'application/53_Wireless_Dongle_Auth_Bypass.py',
    description: '无线CarPlay/AA适配器硬编码WiFi凭据和认证绕过',
    impact: '适配器完全控制',
    remediation: '使用强密码,更新固件',
    requiredParams: ['ip'],
    codeSnippet: '# Wireless Dongle Auth Bypass',
  },
  {
    id: 'POC-APP-010', name: 'OTA Update MITM Interception',
    category: Category.ADVANCED, severity: Severity.CRITICAL, cvssScore: 8.5,
    pocFile: 'advanced/54_OTA_MITM_Interception.py',
    description: '检测OTA更新通道是否使用自签名证书(MITM风险)',
    impact: '固件篡改/恶意更新注入',
    remediation: '实施证书固定和端到端加密',
    requiredParams: ['ip'],
    codeSnippet: '# OTA Update MITM Interception',
  },
  {
    id: 'POC-ADV-001', name: 'RF Keyfob Signal Replay',
    category: Category.ADVANCED, severity: Severity.HIGH, cvssScore: 6.5,
    cveId: 'CVE-2022-27254',
    pocFile: 'advanced/55_RF_Keyfob_Replay.py',
    description: '录制/重放433.92MHz钥匙遥控解锁信号',
    impact: '未授权车辆解锁',
    remediation: '实施滚动码',
    requiredParams: [],
    codeSnippet: '# RF Keyfob Signal Replay',
  },
  {
    id: 'POC-ADV-002', name: 'GPS Signal Spoofing',
    category: Category.ADVANCED, severity: Severity.HIGH, cvssScore: 7.0,
    pocFile: 'advanced/56_GPS_Spoofing.py',
    description: '使用HackRF广播伪造GPS L1信号',
    impact: '导航偏移/ADAS定位错误',
    remediation: '实施认证GPS(Galileo OSNMA)',
    requiredParams: [],
    codeSnippet: '# GPS Signal Spoofing',
  },
  {
    id: 'POC-ADV-003', name: 'TPMS Signal Spoofing',
    category: Category.ADVANCED, severity: Severity.MEDIUM, cvssScore: 5.0,
    pocFile: 'advanced/57_TPMS_Signal_Spoofing.py',
    description: '伪造TPMS传感器信号(315/433MHz)发送异常胎压数据',
    impact: '虚假胎压告警',
    remediation: 'TPMS数据认证和完整性校验',
    requiredParams: [],
    codeSnippet: '# TPMS Signal Spoofing',
  },
  {
    id: 'POC-ADV-004', name: 'V2X BSM Message Injection',
    category: Category.ADVANCED, severity: Severity.HIGH, cvssScore: 7.5,
    pocFile: 'advanced/58_V2X_BSM_Injection.py',
    description: '伪造V2X BSM消息注入虚假车辆位置和速度信息',
    impact: '路径规划干扰/碰撞风险',
    remediation: '实施V2X PKI证书验证',
    requiredParams: ['ip'],
    codeSnippet: '# V2X BSM Message Injection',
  },
  {
    id: 'POC-ADV-005', name: 'Firmware Update TOCTOU Race',
    category: Category.ADVANCED, severity: Severity.CRITICAL, cvssScore: 8.1,
    pocFile: 'advanced/59_FW_Update_TOCTOU.py',
    description: '固件更新签名验证TOCTOU竞态条件',
    impact: '安装未签名/恶意固件',
    remediation: '实施原子文件操作',
    requiredParams: [],
    codeSnippet: '# Firmware Update TOCTOU Race',
  },
  {
    id: 'POC-ADV-006', name: 'QNX Unsigned Firmware Image',
    category: Category.ADVANCED, severity: Severity.HIGH, cvssScore: 7.0,
    pocFile: 'advanced/60_QNX_Unsigned_Firmware.py',
    description: '构造带后门的QNX IFS映像绕过签名验证',
    impact: '持久化后门安装',
    remediation: '验证固件映像签名',
    requiredParams: [],
    codeSnippet: '# QNX Unsigned Firmware Image',
  },
  {
    id: 'POC-ADV-007',
    name: 'USB Unsigned Firmware Update (Android/Linux)',
    category: Category.ADVANCED,
    severity: Severity.CRITICAL,
    cvssScore: 9.8,
    cveId: 'N/A',
    pocFile: 'advanced/61_USB_Unsigned_Update.py',
    description: '生成 Android/Linux IVI 专用伪造 update.zip 绕过签名验证',
    impact: '物理接触下刷入恶意固件',
    remediation: '强制 Recovery 模式校验证书链',
    requiredParams: [],
    codeSnippet: '# USB Unsigned Update PoC',
  },
];
