#!/usr/bin/env python3
import base64
from pathlib import Path


SERVER_DIR = Path(__file__).resolve().parent
POCS_DIR = SERVER_DIR / "pocs"
OUTPUT = SERVER_DIR / "generated_poc_registry.py"


def main() -> int:
    entries = []
    for path in sorted(POCS_DIR.rglob("*.py")):
        if ".venv" in path.parts:
            continue
        rel_path = path.relative_to(POCS_DIR).as_posix()
        encoded = base64.b64encode(path.read_bytes()).decode("ascii")
        entries.append((rel_path, encoded))

    lines = [
        "# Auto-generated by server/generate_poc_registry.py",
        "",
        "POC_CODE_B64_MAP = {",
    ]
    for rel_path, encoded in entries:
        lines.append(f"    {rel_path!r}: {encoded!r},")
    lines.extend([
        "}",
        "",
    ])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(entries)} embedded modules to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
