"""initial_schema

Revision ID: 8763c54bbdfd
Revises: 
Create Date: 2026-07-09 12:13:13.304389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8763c54bbdfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('trace_id', sa.String(length=120), nullable=True),
    sa.Column('artifact_type', sa.String(length=40), nullable=False),
    sa.Column('poc_filename', sa.String(length=255), nullable=True),
    sa.Column('poc_name', sa.String(length=255), nullable=True),
    sa.Column('target_ip', sa.String(length=50), nullable=True),
    sa.Column('target_mac', sa.String(length=50), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_artifacts_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_artifacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_artifacts_poc_filename'), ['poc_filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_artifacts_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_artifacts_trace_id'), ['trace_id'], unique=False)

    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('target_ip', sa.String(length=50), nullable=True),
    sa.Column('target_mac', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supervisor_metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('target_ip', sa.String(length=50), nullable=True),
    sa.Column('model_profile', sa.String(length=120), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('adjustments_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supervisor_metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supervisor_metric_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supervisor_metric_snapshots_session_id'), ['session_id'], unique=False)

    op.create_table('user_ai_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_ai_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_ai_configs_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ai_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_ai_configs_user_id'))

    op.drop_table('user_ai_configs')
    with op.batch_alter_table('supervisor_metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supervisor_metric_snapshots_session_id'))
        batch_op.drop_index(batch_op.f('ix_supervisor_metric_snapshots_created_at'))

    op.drop_table('supervisor_metric_snapshots')
    op.drop_table('scan_history')
    with op.batch_alter_table('execution_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_artifacts_trace_id'))
        batch_op.drop_index(batch_op.f('ix_execution_artifacts_session_id'))
        batch_op.drop_index(batch_op.f('ix_execution_artifacts_poc_filename'))
        batch_op.drop_index(batch_op.f('ix_execution_artifacts_created_at'))
        batch_op.drop_index(batch_op.f('ix_execution_artifacts_artifact_type'))

    op.drop_table('execution_artifacts')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
